version: '3'

services: 
    elasticsearch:
        container_name: "elasticsearch"
        image: elasticsearch:7.13.4
        ports: 
            - 9200:9200
            - 9300:9300
        environment: 
            - discovery.type=single-node

    redis:
        container_name: "redis"
        image: redis
        ports: 
           - 6379:6379
